### ISSUE TITLE
AssertionError in border_correction

### ISSUE THREAD

**Issue by macraild** [Arseha/peakonly#7]
Hi,

Feature detection on one of my datasets raised the following error:

Traceback (most recent call last):
  File "C:\Users\macraild\progs\peakonly\gui_utils\threading.py", line 72, in run
    result = self.function(*self.args, **self.kwargs)
  File "C:\Users\macraild\progs\peakonly\processing_utils\runner.py", line 147, in __call__
    features = self._batch_run(files, progress_callback, operation_callback)
  File "C:\Users\macraild\progs\peakonly\processing_utils\runner.py", line 261, in _batch_run
    border_correction(component, borders)
  File "C:\Users\macraild\progs\peakonly\processing_utils\run_utils.py", line 326, in border_correction
    assert np.abs(counter_order[-1] - counter_order[-2]) == 1, "almost impossible case :)"
AssertionError: almost impossible case :)

Simply commenting out the offending assert allowed processing to proceed, and I can't see any obvious errors in  the results, but I dont understand enough of what is going on here to know if this is a safe workaround. Please let me know if there is anything I can do to help track down this bug, but also if this can be safely ignored, or if it points to a bigger problem.

**Comment by macraild** [comment]
Thanks, changing the minimum ROI length seems to avoid the bug.
